# **Natural Language Processing - 1**

In [10]:
## Importing Libraries
import numpy as np
import pandas as pd

In [11]:
df = pd.read_csv('./content/IMDB Dataset - IMDB Dataset.csv', on_bad_lines='skip', engine='python')
df.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [12]:
df['review'][3]

"Basically there's a family where a little boy (Jake) thinks there's a zombie in his closet & his parents are fighting all the time.<br /><br />This movie is slower than a soap opera... and suddenly, Jake decides to become Rambo and kill the zombie.<br /><br />OK, first of all when you're going to make a film you must Decide if its a thriller or a drama! As a drama the movie is watchable. Parents are divorcing & arguing like in real life. And then we have Jake with his closet which totally ruins all the film! I expected to see a BOOGEYMAN similar movie, and instead i watched a drama with some meaningless thriller spots.<br /><br />3 out of 10 just for the well playing parents & descent dialogs. As for the shots with Jake: just ignore them."

## Step: 1 --> Lowercasing

In [13]:
df['review'][3].lower()

"basically there's a family where a little boy (jake) thinks there's a zombie in his closet & his parents are fighting all the time.<br /><br />this movie is slower than a soap opera... and suddenly, jake decides to become rambo and kill the zombie.<br /><br />ok, first of all when you're going to make a film you must decide if its a thriller or a drama! as a drama the movie is watchable. parents are divorcing & arguing like in real life. and then we have jake with his closet which totally ruins all the film! i expected to see a boogeyman similar movie, and instead i watched a drama with some meaningless thriller spots.<br /><br />3 out of 10 just for the well playing parents & descent dialogs. as for the shots with jake: just ignore them."

In [14]:
df['review'] = df['review'].str.lower()

In [15]:
df.head()

                                              review sentiment
0  one of the other reviewers has mentioned that ...  positive
1  a wonderful little production. <br /><br />the...  positive
2  i thought this was a wonderful way to spend ti...  positive
3  basically there's a family where a little boy ...  negative
4  petter mattei's "love in the time of money" is...  positive

## Step: 2 --> Remove HTML Tags

In [16]:
import re
def remove_html_tags(text):
  pattern = re.compile('<.*?>')
  return pattern.sub(r'', text)

In [17]:
text = "<html><body><p> Movie1 </p><p> Click here to <a href = 'http://google.com'>download</a></p>"
remove_html_tags(text)

' Movie1  Click here to download'

In [18]:
df['review'] = df['review'].apply(remove_html_tags)
df.head()

                                              review sentiment
0  one of the other reviewers has mentioned that ...  positive
1  a wonderful little production. the filming tec...  positive
2  i thought this was a wonderful way to spend ti...  positive
3  basically there's a family where a little boy ...  negative
4  petter mattei's "love in the time of money" is...  positive

In [19]:
## If you want to remove url from text
def remove_url(text):
  pattern = re.compile(r'https?://\S+|www\.\S+')
  return pattern.sub(r'', text)

In [20]:
from os import remove
text1 = 'For notebook click https://www.deture.com/delta/note123acc'
remove_url(text1)

'For notebook click '

In [21]:
df['review'] = df['review'].apply(remove_url)
df.head()

                                              review sentiment
0  one of the other reviewers has mentioned that ...  positive
1  a wonderful little production. the filming tec...  positive
2  i thought this was a wonderful way to spend ti...  positive
3  basically there's a family where a little boy ...  negative
4  petter mattei's "love in the time of money" is...  positive

## Step: 3 --> Remove Punctuation

In [22]:
import string
string.punctuation

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [23]:
exclude = string.punctuation

def remove_punc(text):
  for char in exclude:
    text = text.replace(char, '')
  return text

In [24]:
test = 'string. With. Punctuation?'
remove_punc(test)

'string With Punctuation'

In [25]:
df['review'] = df['review'].apply(remove_punc)
df

                                                  review sentiment
0      one of the other reviewers has mentioned that ...  positive
1      a wonderful little production the filming tech...  positive
2      i thought this was a wonderful way to spend ti...  positive
3      basically theres a family where a little boy j...  negative
4      petter matteis love in the time of money is a ...  positive
...                                                  ...       ...
49995  i thought this movie did a down right good job...  positive
49996  bad plot bad dialogue bad acting idiotic direc...  negative
49997  i am a catholic taught in parochial elementary...  negative
49998  im going to have to disagree with the previous...  negative
49999  no one expects the star trek movies to be high...  negative

[50000 rows x 2 columns]

## Step: 4 --> Chatword Treatment

In [26]:
chat_words = {"u2" : "you too", "BBL" : "Be Back Later", "GAL" : "Get a life"}
chat_words

{'u2': 'you too', 'BBL': 'Be Back Later', 'GAL': 'Get a life'}

In [27]:
def chat_conversion(text):
  new_text = []
  for word in text.split():
    if word.upper() in chat_words:
      new_text.append(chat_words[word.upper()])
    else:
      new_text.append(word)
  return "".join(new_text)

In [28]:
chat_conversion("BBL")

'Be Back Later'

## Step: 5 --> Spelling Correction

In [31]:
# !pip install TextBlob

Collecting TextBlob
  Downloading textblob-0.20.0-py3-none-any.whl.metadata (4.0 kB)
Collecting nltk>=3.9 (from TextBlob)
  Downloading nltk-3.9.4-py3-none-any.whl.metadata (3.2 kB)
Collecting click (from nltk>=3.9->TextBlob)
  Using cached click-8.3.3-py3-none-any.whl.metadata (2.6 kB)
Collecting joblib (from nltk>=3.9->TextBlob)
  Using cached joblib-1.5.3-py3-none-any.whl.metadata (5.5 kB)
Collecting regex>=2021.8.3 (from nltk>=3.9->TextBlob)
  Using cached regex-2026.5.9-cp310-cp310-win_amd64.whl.metadata (41 kB)
Collecting tqdm (from nltk>=3.9->TextBlob)
  Using cached tqdm-4.67.3-py3-none-any.whl.metadata (57 kB)
Requirement already satisfied: colorama in c:\users\deven\appdata\roaming\python\python310\site-packages (from click->nltk>=3.9->TextBlob) (0.4.6)
Downloading textblob-0.20.0-py3-none-any.whl (624 kB)
   ---------------------------------------- 0.0/625.0 kB ? eta -:--:--
   ---------------------------------------- 625.0/625.0 kB 7.7 MB/s  0:00:00
Downloading nltk-3.9.4-py3-none-any.whl (1.6 MB)
   ---------------------------------------- 0.0/1.6 MB ? eta -:--:--
   ---------------------------------------- 1.6/1.6 MB 10.3 MB/s  0:00:00
Using cached regex-2026.5.9-cp310-cp310-win_amd64.whl (278 kB)
Using cached click-8.3.3-py3-none-any.whl (110 kB)
Using cached joblib-1.5.3-py3-none-any.whl (309 kB)
Using cached tqdm-4.67.3-py3-none-any.whl (78 kB)
Installing collected packages: tqdm, regex, joblib, click, nltk, TextBlob

   ------ --------------------------------- 1/6 [regex]
   ------------- -------------------------- 2/6 [joblib]
   ------------- -------------------------- 2/6 [joblib]
   ------------- -------------------------- 2/6 [joblib]
   -------------------- ------------------- 3/6 [click]
   -------------------------- ------------- 4/6 [nltk]
   -------------------------- ------------- 4/6 [nltk]
   -------------------------- ------------- 4/6 [nltk]
   -------------------------- ------------- 4/6 [nltk]
   -------------------------- ------------- 4/6 [nltk]
   -------------------------- ------------- 4/6 [nltk]
   -------------------------- ------------- 4/6 [nltk]
   -------------------------- ------------- 4/6 [nltk]
   -------------------------- ------------- 4/6 [nltk]
   -------------------------- ------------- 4/6 [nltk]
   -------------------------- ------------- 4/6 [nltk]
   -------------------------- ------------- 4/6 [nltk]
   -------------------------- ------------- 4/6 [nltk]
   --------------------------------- ------ 5/6 [TextBlob]
   ---------------------------------------- 6/6 [TextBlob]

Successfully installed TextBlob-0.20.0 click-8.3.3 joblib-1.5.3 nltk-3.9.4 regex-2026.5.9 tqdm-4.67.3

In [32]:
from textblob import TextBlob

incorrect = "ceertain conditionas seveal ggenerations aree modified in the saame maner."
textblb = TextBlob(incorrect)
textblb.correct().string

'certain conditions several generations are modified in the same manner.'

## Step: 6 --> Removing Stopwords

In [33]:
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords

STOPWORDS = set(stopwords.words('english'))

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\deven\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [35]:
def remove_stopwords(text: str):
  new_text = []
  for word in text.split():
    if word in STOPWORDS:
      new_text.append('')
    else:
      new_text.append(word)

  x = new_text[:]
  new_text.clear()
  return " ".join(x)

remove_stopwords('probably my all-time favourite movie, a story of selflessness, sacrifice and dedicated to a noble cause')

'probably  all-time favourite movie,  story  selflessness, sacrifice  dedicated   noble cause'