## Text Summarization

### 1. Bag of Words

In [83]:
import numpy as np
import pandas as pd

df = pd.DataFrame({'text' : ['people watch cricket', 'player was player',
                              'people write comment', 'cricket play comment'],
                   'output' : [1,1,0,0]})

In [84]:
df

                   text  output
0  people watch cricket       1
1     player was player       1
2  people write comment       0
3  cricket play comment       0

In [85]:
## Unique words --> people watch cricket player was write comment play
# [11100000]
# [00021000]
# [10000110]
# [00100011]

In [86]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()

BOW = cv.fit_transform(df['text'])

# Vocab
print(cv.vocabulary_)

{'people': 2, 'watch': 6, 'cricket': 1, 'player': 4, 'was': 5, 'write': 7, 'comment': 0, 'play': 3}

In [87]:
print(BOW[0].toarray())
print(BOW[1].toarray())

[[0 1 1 0 0 0 1 0]]
[[0 0 0 0 2 1 0 0]]

In [88]:
cv.transform(["cricket watch and write comment of cricket comment"]).toarray()

array([[2, 2, 0, 0, 0, 0, 1, 1]])

### 2. N-Grams

In [89]:
v = CountVectorizer(ngram_range= (1, 2))
bow = v.fit_transform(df['text'])
df['text']

0    people watch cricket
1       player was player
2    people write comment
3    cricket play comment
Name: text, dtype: object

In [90]:
# vocab
print(v.vocabulary_)

{'people': 3, 'watch': 12, 'cricket': 1, 'people watch': 4, 'watch cricket': 13, 'player': 8, 'was': 10, 'player was': 9, 'was player': 11, 'write': 14, 'comment': 0, 'people write': 5, 'write comment': 15, 'play': 6, 'cricket play': 2, 'play comment': 7}

### 3. TF-IDF (Term Frequency - Inverse Document Frequency)

In [91]:
# TF(t, d) = (number of occurance of term t in document d) / (total number of terms in documnt d)

# Example --> d1 = people watch cricket
# tf(people, d1) = 1 / 3

# d2 = match was match
# tf(match, d2) = 2 / 3

# IDF(t) = log(Total number of documents in corpus / Number of documents with term t in them)
# Here corpus means number of sentences

# Example ==>
# d1 = people watch cricket.
# d2 = cricket was cricket.
# d3 = people write comment.
# d4 = cricket write comment.

# idf(cricket) = log(4/4)
# idf(people) = log(4/2)

In [92]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf = TfidfVectorizer()

tfidf.fit_transform(df['text'])

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 11 stored elements and shape (4, 8)>

In [93]:
tfidf.fit_transform(df['text']).toarray()

array([[0.        , 0.52640543, 0.52640543, 0.        , 0.        ,
        0.        , 0.66767854, 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.89442719,
        0.4472136 , 0.        , 0.        ],
       [0.52640543, 0.        , 0.52640543, 0.        , 0.        ,
        0.        , 0.        , 0.66767854],
       [0.52640543, 0.52640543, 0.        , 0.66767854, 0.        ,
        0.        , 0.        , 0.        ]])

In [94]:
print(tfidf.idf_)
print(tfidf.get_feature_names_out())

[1.51082562 1.51082562 1.51082562 1.91629073 1.91629073 1.91629073
 1.91629073 1.91629073]
['comment' 'cricket' 'people' 'play' 'player' 'was' 'watch' 'write']

## Dataset -> IMDB Dataset

In [95]:
df = pd.read_csv('/content/IMDB Dataset - IMDB Dataset.csv')
df.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [96]:
## Lowercasing
data = df.loc[0:20].copy()
data['review'] = data['review'].str.lower()

In [97]:
## Removing HTML tags
import re
def remove_html_tags(text):
  pattern = re.compile('<.*?>')
  return pattern.sub(r'', text)

data['review'] = data['review'].apply(remove_html_tags)

In [98]:
## Removing URL's
def remove_url(text):
  pattern = re.compile(r'https?://\S+|www\.\S+')
  return pattern.sub(r'', text)
data['review'] = data['review'].apply(remove_url)

In [99]:
# import string
# string.punctuation

# exclude = string.punctuation

# def remove_punc(text):
#   for char in exclude:
#     text = text.replace(char, '')
#   return text
# data['review'] = data['review'].apply(remove_punc)

In [100]:
# import nltk
# nltk.download('stopwords')
# from nltk.corpus import stopwords

# STOPWORDS = set(stopwords.words('english'))

# def remove_stopwords(text: str):
#   new_text = []
#   for word in text.split():
#     if word in STOPWORDS:
#       new_text.append('')
#     else:
#       new_text.append(word)

#   x = new_text[:]
#   new_text.clear()
#   return "".join(x)

# data['review'] = data['review'].apply(remove_stopwords)

In [101]:
data

                                               review sentiment
0   one of the other reviewers has mentioned that ...  positive
1   a wonderful little production. the filming tec...  positive
2   i thought this was a wonderful way to spend ti...  positive
3   basically there's a family where a little boy ...  negative
4   petter mattei's "love in the time of money" is...  positive
5   probably my all-time favorite movie, a story o...  positive
6   i sure would like to see a resurrection of a u...  positive
7   this show was an amazing, fresh & innovative i...  negative
8   encouraged by the positive comments about this...  negative
9   if you like original gut wrenching laughter yo...  positive
10  phil the alien is one of those quirky films wh...  negative
11  i saw this movie when i was about 12 when it c...  negative
12  so im not a big fan of boll's work but then ag...  negative
13  the cast played shakespeare.shakespeare lost.i...  negative
14  this a fantastic movie of three prisoners who ...  positive
15  kind of drawn in by the erotic scenes, only to...  negative
16  some films just simply should not be remade. t...  positive
17  this movie made it into one of my top 10 most ...  negative
18  i remember this film,it was the first film i h...  positive
19  an awful film! it must have been up against so...  negative
20  after the success of die hard and it's sequels...  positive

In [102]:
import nltk
from nltk.stem import WordNetLemmatizer
nltk.download('wordnet')
nltk.download('omw-1.4')

lemmatizer = WordNetLemmatizer()

data['review'] = data['review'].apply(lambda x: lemmatizer.lemmatize(x))

[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to /root/nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!

In [103]:
data

                                               review sentiment
0   one of the other reviewers has mentioned that ...  positive
1   a wonderful little production. the filming tec...  positive
2   i thought this was a wonderful way to spend ti...  positive
3   basically there's a family where a little boy ...  negative
4   petter mattei's "love in the time of money" is...  positive
5   probably my all-time favorite movie, a story o...  positive
6   i sure would like to see a resurrection of a u...  positive
7   this show was an amazing, fresh & innovative i...  negative
8   encouraged by the positive comments about this...  negative
9   if you like original gut wrenching laughter yo...  positive
10  phil the alien is one of those quirky films wh...  negative
11  i saw this movie when i was about 12 when it c...  negative
12  so im not a big fan of boll's work but then ag...  negative
13  the cast played shakespeare.shakespeare lost.i...  negative
14  this a fantastic movie of three prisoners who ...  positive
15  kind of drawn in by the erotic scenes, only to...  negative
16  some films just simply should not be remade. t...  positive
17  this movie made it into one of my top 10 most ...  negative
18  i remember this film,it was the first film i h...  positive
19  an awful film! it must have been up against so...  negative
20  after the success of die hard and it's sequels...  positive

In [104]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf = TfidfVectorizer()

tfidf.fit_transform(data['review']).toarray()

array([[0.        , 0.        , 0.        , ..., 0.        , 0.04366977,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.0748971 , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.09353528,
        0.        ]])

In [105]:
print(tfidf.idf_)
print(tfidf.vocabulary_)

[2.70474809 3.39789527 3.39789527 ... 2.70474809 2.70474809 3.39789527]
{'one': 736, 'of': 727, 'the': 1066, 'other': 744, 'reviewers': 871, 'has': 472, 'mentioned': 665, 'that': 1064, 'after': 29, 'watching': 1173, 'just': 559, 'oz': 753, 'episode': 323, 'you': 1228, 'll': 610, 'be': 96, 'hooked': 495, 'they': 1074, 'are': 66, 'right': 876, 'as': 74, 'this': 1080, 'is': 541, 'exactly': 336, 'what': 1184, 'happened': 465, 'with': 1199, 'me': 657, 'first': 386, 'thing': 1075, 'struck': 1023, 'about': 12, 'was': 1166, 'its': 545, 'brutality': 141, 'and': 53, 'unflinching': 1132, 'scenes': 907, 'violence': 1153, 'which': 1187, 'set': 938, 'in': 523, 'from': 406, 'word': 1207, 'go': 431, 'trust': 1116, 'not': 718, 'show': 953, 'for': 394, 'faint': 359, 'hearted': 478, 'or': 739, 'timid': 1094, 'pulls': 827, 'no': 714, 'punches': 828, 'regards': 853, 'to': 1097, 'drugs': 293, 'sex': 940, 'hardcore': 470, 'classic': 183, 'use': 1138, 'it': 543, 'called': 150, 'nickname': 712, 'given': 424, 'oswald': 743, 'maximum': 654, 'security': 926, 'state': 1006, 'penitentary': 768, 'focuses': 391, 'mainly': 637, 'on': 735, 'emerald': 308, 'city': 181, 'an': 52, 'experimental': 346, 'section': 925, 'prison': 816, 'where': 1186, 'all': 44, 'cells': 167, 'have': 473, 'glass': 427, 'fronts': 407, 'face': 353, 'inwards': 539, 'so': 975, 'privacy': 818, 'high': 490, 'agenda': 33, 'em': 307, 'home': 494, 'many': 647, 'aryans': 73, 'muslims': 693, 'gangstas': 415, 'latinos': 582, 'christians': 179, 'italians': 544, 'irish': 540, 'more': 684, 'scuffles': 920, 'death': 241, 'stares': 1001, 'dodgy': 279, 'dealings': 240, 'shady': 942, 'agreements': 36, 'never': 706, 'far': 367, 'away': 84, 'would': 1215, 'say': 900, 'main': 636, 'appeal': 63, 'due': 295, 'fact': 355, 'goes': 432, 'shows': 954, 'wouldn': 1216, 'dare': 233, 'forget': 395, 'pretty': 813, 'pictures': 783, 'painted': 758, 'mainstream': 638, 'audiences': 79, 'charm': 173, 'romance': 881, 'doesn': 281, 'mess': 668, 'around': 69, 'ever': 330, 'saw': 899, 'nasty': 699, 'surreal': 1041, 'couldn': 214, 'ready': 841, 'but': 148, 'watched': 1172, 'developed': 254, 'taste': 1049, 'got': 437, 'accustomed': 15, 'levels': 596, 'graphic': 440, 'injustice': 527, 'crooked': 223, 'guards': 449, 'who': 1191, 'sold': 977, 'out': 748, 'nickel': 711, 'inmates': 528, 'kill': 568, 'order': 740, 'get': 419, 'well': 1181, 'mannered': 646, 'middle': 670, 'class': 182, 'being': 103, 'turned': 1122, 'into': 535, 'bitches': 115, 'their': 1068, 'lack': 578, 'street': 1022, 'skills': 967, 'experience': 345, 'may': 655, 'become': 99, 'comfortable': 194, 'uncomfortable': 1129, 'viewing': 1151, 'thats': 1065, 'if': 514, 'can': 153, 'touch': 1105, 'your': 1230, 'darker': 235, 'side': 956, 'wonderful': 1203, 'little': 608, 'production': 821, 'filming': 380, 'technique': 1052, 'very': 1146, 'unassuming': 1127, 'old': 732, 'time': 1092, 'bbc': 95, 'fashion': 368, 'gives': 425, 'comforting': 195, 'sometimes': 983, 'discomforting': 273, 'sense': 933, 'realism': 843, 'entire': 321, 'piece': 784, 'actors': 20, 'extremely': 350, 'chosen': 178, 'michael': 669, 'sheen': 946, 'only': 737, 'polari': 802, 'he': 476, 'voices': 1156, 'down': 285, 'pat': 766, 'too': 1101, 'truly': 1115, 'see': 927, 'seamless': 923, 'editing': 302, 'guided': 451, 'by': 149, 'references': 852, 'williams': 1196, 'diary': 259, 'entries': 322, 'worth': 1213, 'terrificly': 1059, 'written': 1221, 'performed': 774, 'masterful': 650, 'great': 441, 'master': 649, 'comedy': 192, 'his': 492, 'life': 599, 'really': 845, 'comes': 193, 'things': 1076, 'fantasy': 366, 'guard': 448, 'rather': 838, 'than': 1062, 'traditional': 1108, 'dream': 290, 'techniques': 1053, 'remains': 857, 'solid': 979, 'then': 1071, 'disappears': 268, 'plays': 793, 'our': 746, 'knowledge': 574, 'senses': 934, 'particularly': 764, 'concerning': 202, 'orton': 742, 'halliwell': 461, 'sets': 939, 'flat': 389, 'murals': 692, 'decorating': 246, 'every': 331, 'surface': 1039, 'terribly': 1058, 'done': 283, 'thought': 1082, 'way': 1175, 'spend': 991, 'hot': 500, 'summer': 1033, 'weekend': 1180, 'sitting': 965, 'air': 39, 'conditioned': 204, 'theater': 1067, 'light': 600, 'plot': 796, 'simplistic': 960, 'dialogue': 258, 'witty': 1201, 'characters': 172, 'likable': 601, 'even': 328, 'bread': 133, 'suspected': 1042, 'serial': 936, 'killer': 569, 'while': 1188, 'some': 980, 'disappointed': 269, 'when': 1185, 'realize': 844, 'match': 651, 'point': 800, 'risk': 878, 'addiction': 24, 'proof': 825, 'woody': 1206, 'allen': 45, 'still': 1011, 'fully': 410, 'control': 212, 'style': 1025, 'us': 1137, 'grown': 447, 'love': 624, 'most': 685, 'laughed': 584, 'at': 75, 'comedies': 191, 'years': 1224, 'decade': 242, 've': 1144, 'been': 100, 'impressed': 521, 'scarlet': 904, 'johanson': 552, 'she': 945, 'managed': 644, 'tone': 1100, 'her': 486, 'sexy': 941, 'image': 517, 'jumped': 556, 'average': 80, 'spirited': 994, 'young': 1229, 'woman': 1202, 'crown': 225, 'jewel': 551, 'career': 159, 'wittier': 1200, 'devil': 256, 'wears': 1178, 'prada': 809, 'interesting': 534, 'superman': 1034, 'friends': 404, 'basically': 94, 'there': 1072, 'family': 362, 'boy': 131, 'jake': 549, 'thinks': 1079, 'zombie': 1231, 'closet': 187, 'parents': 762, 'fighting': 378, 'movie': 688, 'slower': 970, 'soap': 976, 'opera': 738, 'suddenly': 1031, 'decides': 244, 'rambo': 836, 'ok': 731, 're': 839, 'going': 433, 'make': 640, 'film': 379, 'must': 694, 'decide': 243, 'thriller': 1085, 'drama': 288, 'watchable': 1171, 'divorcing': 277, 'arguing': 68, 'like': 602, 'real': 842, 'we': 1176, 'totally': 1104, 'ruins': 889, 'expected': 344, 'boogeyman': 124, 'similar': 958, 'instead': 532, 'meaningless': 659, 'spots': 996, '10': 0, 'playing': 792, 'descent': 251, 'dialogs': 257, 'shots': 951, 'ignore': 515, 'them': 1069, 'petter': 779, 'mattei': 653, 'money': 682, 'visually': 1154, 'stunning': 1024, 'watch': 1170, 'mr': 690, 'offers': 729, 'vivid': 1155, 'portrait': 804, 'human': 505, 'relations': 854, 'seems': 928, 'telling': 1055, 'power': 808, 'success': 1028, 'do': 278, 'people': 769, 'different': 265, 'situations': 966, 'encounter': 310, 'variation': 1143, 'arthur': 71, 'schnitzler': 911, 'play': 789, 'same': 894, 'theme': 1070, 'director': 267, 'transfers': 1109, 'action': 18, 'present': 812, 'new': 707, 'york': 1227, 'these': 1073, 'meet': 661, 'connect': 205, 'each': 298, 'connected': 206, 'another': 56, 'next': 709, 'person': 777, 'know': 573, 'previous': 815, 'contact': 209, 'stylishly': 1026, 'sophisticated': 985, 'luxurious': 632, 'look': 616, 'taken': 1046, 'how': 502, 'live': 609, 'world': 1210, 'own': 752, 'habitat': 455, 'gets': 420, 'souls': 988, 'picture': 782, 'stages': 998, 'loneliness': 614, 'inhabits': 526, 'big': 111, 'best': 107, 'place': 786, 'find': 383, 'sincere': 963, 'fulfillment': 408, 'discerns': 272, 'case': 163, 'acting': 17, 'good': 436, 'under': 1131, 'direction': 266, 'steve': 1010, 'buscemi': 146, 'rosario': 887, 'dawson': 239, 'carol': 161, 'kane': 561, 'imperioli': 519, 'adrian': 25, 'grenier': 443, 'rest': 867, 'talented': 1048, 'cast': 165, 'come': 189, 'alive': 43, 'wish': 1198, 'luck': 628, 'await': 82, 'anxiously': 57, 'work': 1209, 'probably': 819, 'my': 696, 'favorite': 371, 'story': 1019, 'selflessness': 931, 'sacrifice': 893, 'dedication': 247, 'noble': 715, 'cause': 166, 'preachy': 810, 'boring': 125, 'despite': 252, 'having': 475, 'seen': 929, '15': 2, 'times': 1093, 'last': 580, '25': 7, 'paul': 767, 'lukas': 629, 'performance': 772, 'brings': 138, 'tears': 1050, 'eyes': 351, 'bette': 108, 'davis': 238, 'few': 376, 'sympathetic': 1044, 'roles': 879, 'delight': 248, 'kids': 566, 'grandma': 439, 'says': 902, 'dressed': 291, 'up': 1136, 'midgets': 671, 'children': 176, 'makes': 641, 'fun': 411, 'mother': 686, 'slow': 969, 'awakening': 83, 'happening': 466, 'roof': 884, 'believable': 104, 'startling': 1004, 'had': 457, 'dozen': 286, 'thumbs': 1087, 'sure': 1037, 'resurrection': 868, 'dated': 236, 'seahunt': 922, 'series': 937, 'tech': 1051, 'today': 1098, 'bring': 137, 'back': 86, 'kid': 565, 'excitement': 341, 'grew': 444, 'black': 119, 'white': 1190, 'tv': 1123, 'gunsmoke': 452, 'were': 1182, 'hero': 488, 'week': 1179, 'vote': 1158, 'comeback': 190, 'sea': 921, 'hunt': 509, 'need': 702, 'change': 170, 'pace': 754, 'water': 1174, 'adventure': 27, 'oh': 730, 'thank': 1063, 'outlet': 749, 'view': 1150, 'viewpoints': 1152, 'movies': 689, 'any': 58, 'ole': 734, 'believe': 105, 'wanna': 1162, 'nice': 710, 'read': 840, 'plus': 799, 'points': 801, 'rhymes': 873, 'lines': 605, 'let': 594, 'submit': 1027, 'leave': 589, 'doubt': 284, 'quit': 832, 'lets': 595, 'amazing': 51, 'fresh': 402, 'innovative': 529, 'idea': 513, '70': 8, 'aired': 40, 'brilliant': 136, 'dropped': 292, 'off': 728, '1990': 4, 'funny': 412, 'anymore': 60, 'continued': 210, 'decline': 245, 'further': 413, 'complete': 199, 'waste': 1168, 'disgraceful': 274, 'fallen': 361, 'writing': 1220, 'painfully': 757, 'bad': 87, 'performances': 773, 'almost': 46, 'mildly': 674, 'entertaining': 320, 'respite': 866, 'guest': 450, 'hosts': 499, 'hard': 469, 'creator': 219, 'hand': 462, 'selected': 930, 'original': 741, 'also': 48, 'chose': 177, 'band': 90, 'hacks': 456, 'followed': 392, 'recognize': 849, 'such': 1029, 'brilliance': 135, 'fit': 387, 'replace': 861, 'mediocrity': 660, 'felt': 374, 'give': 423, 'stars': 1002, 'respect': 865, 'made': 635, 'huge': 504, 'now': 721, 'awful': 85, 'encouraged': 312, 'positive': 805, 'comments': 196, 'here': 487, 'looking': 618, 'forward': 399, 'mistake': 679, '950': 11, 'films': 381, 'worst': 1212, 'pacing': 755, 'storyline': 1020, 'soundtrack': 989, 'song': 984, 'lame': 579, 'country': 215, 'tune': 1119, 'played': 790, 'less': 592, 'four': 400, 'looks': 619, 'cheap': 174, 'extreme': 349, 'rarely': 837, 'happy': 467, 'end': 313, 'credits': 220, 'prevents': 814, 'giving': 426, 'score': 915, 'harvey': 471, 'keitel': 563, 'least': 588, 'making': 642, 'bit': 114, 'effort': 304, 'obsessives': 724, 'gut': 453, 'wrenching': 1218, 'laughter': 586, 'will': 1195, 'hell': 480, 'mom': 681, 'liked': 603, 'camp': 152, 'phil': 780, 'alien': 42, 'those': 1081, 'quirky': 831, 'humour': 508, 'based': 93, 'oddness': 726, 'everything': 333, 'actual': 21, 'punchlines': 829, 'odd': 725, 'progressed': 823, 'didn': 261, 'jokes': 554, 'low': 626, 'budget': 143, 'problem': 820, 'itself': 546, 'eventually': 329, 'lost': 620, 'interest': 533, 'imagine': 518, 'stoner': 1017, 'currently': 227, 'partaking': 763, 'something': 982, 'better': 109, 'try': 1117, 'brother': 140, 'planet': 788, '12': 1, 'came': 151, 'recall': 847, 'scariest': 903, 'scene': 906, 'bird': 112, 'eating': 301, 'men': 663, 'dangling': 232, 'helplessly': 483, 'parachutes': 761, 'horror': 497, 'cheesy': 175, 'saturday': 896, 'afternoons': 30, 'tired': 1095, 'formula': 397, 'monster': 683, 'type': 1124, 'usually': 1140, 'included': 524, 'beautiful': 97, 'might': 673, 'daughter': 237, 'professor': 822, 'resolution': 864, 'died': 263, 'care': 158, 'much': 691, 'romantic': 882, 'angle': 54, 'year': 1223, 'predictable': 811, 'plots': 797, 'unintentional': 1133, 'humor': 507, 'later': 581, 'psycho': 826, 'loved': 625, 'star': 1000, 'janet': 550, 'leigh': 591, 'bumped': 144, 'early': 300, 'sat': 895, 'took': 1102, 'notice': 720, 'since': 962, 'screenwriters': 918, 'scary': 905, 'possible': 806, 'worn': 1211, 'rules': 890, 'im': 516, 'fan': 364, 'boll': 122, 'again': 31, 'enjoyed': 317, 'postal': 807, 'maybe': 656, 'apparently': 62, 'bought': 127, 'rights': 877, 'cry': 226, 'long': 615, 'ago': 35, 'before': 101, 'game': 414, 'finsished': 385, 'killing': 570, 'mercs': 667, 'infiltrating': 525, 'secret': 924, 'research': 863, 'labs': 577, 'located': 611, 'tropical': 1113, 'island': 542, 'should': 952, 'warned': 1164, 'schemed': 909, 'together': 1099, 'along': 47, 'legion': 590, 'schmucks': 910, 'feeling': 373, 'loneley': 613, 'invites': 537, 'three': 1083, 'countrymen': 216, 'players': 791, 'names': 698, 'til': 1090, 'schweiger': 913, 'udo': 1125, 'kier': 567, 'ralf': 834, 'moeller': 680, 'actually': 22, 'selfs': 932, 'biz': 117, 'tale': 1047, 'jack': 547, 'carver': 162, 'yes': 1225, 'german': 418, 'hail': 459, 'bratwurst': 132, 'dudes': 294, 'however': 503, 'tils': 1091, 'badass': 88, 'complained': 197, 'staying': 1008, 'true': 1114, 'whole': 1192, 'perspective': 778, 'don': 282, 'looked': 617, 'kicking': 564, 'beyond': 110, 'demented': 250, 'evil': 334, 'mad': 634, 'scientist': 914, 'dr': 287, 'krieger': 576, 'genetically': 416, 'mutated': 695, 'soldiers': 978, 'gms': 430, 'performing': 775, 'top': 1103, 'reminds': 859, 'spoiler': 995, 'vancouver': 1142, 'reason': 846, 'palm': 760, 'trees': 1111, 'rich': 874, 'lumberjack': 631, 'woods': 1205, 'haven': 474, 'gone': 435, 'started': 1003, 'mehehe': 662, 'cannot': 154, 'stay': 1007, 'bolls': 123, 'shenanigans': 947, 'delivers': 249, 'meaning': 658, 'suck': 1030, 'mentioning': 666, 'imply': 520, 'did': 260, 'areas': 67, 'boat': 121, 'until': 1135, 'cromed': 222, 'albino': 41, 'squad': 997, 'enters': 319, 'laugh': 583, 'reeks': 851, 'scheisse': 908, 'poop': 803, 'simpletons': 959, 'fa': 352, 'take': 1045, 'wiff': 1194, 'ahead': 37, 'btw': 142, 'annoying': 55, 'sidekick': 957, 'shoot': 949, 'him': 491, 'minutes': 678, 'screen': 917, 'shakespeare': 943, 'appreciate': 65, 'trying': 1118, 'masses': 648, 'why': 1193, 'ruin': 888, 'because': 98, 'scottish': 916, 'certain': 168, 'rev': 870, 'bowdler': 128, 'hence': 484, 'bowdlerization': 129, 'tried': 1112, 'victorian': 1148, 'era': 324, 'words': 1208, 'improve': 522, 'perfection': 770, 'write': 1219, 'ten': 1056, 'text': 1061, 'english': 315, 'composition': 200, 'forte': 398, 'keep': 562, 'saying': 901, 'does': 280, 'cut': 228, 'fantastic': 365, 'prisoners': 817, 'famous': 363, 'george': 417, 'clooney': 186, 'roll': 880, 'man': 643, 'constant': 207, 'sorrow': 986, 'recommand': 850, 'everybody': 332, 'greetings': 442, 'bart': 91, 'kind': 571, 'drawn': 289, 'erotic': 325, 'amateurish': 50, 'unbelievable': 1128, 'bits': 116, 'sort': 987, 'school': 912, 'project': 824, 'rosanna': 886, 'arquette': 70, 'thinking': 1078, 'stock': 1015, 'bizarre': 118, 'supposed': 1036, 'midwest': 672, 'town': 1106, 'involved': 538, 'lessons': 593, 'learned': 587, 'insights': 530, 'stilted': 1012, 'quite': 833, 'ridiculous': 875, 'lots': 622, 'skin': 968, 'intrigues': 536, 'videotaped': 1149, 'nonsense': 717, 'bisexual': 113, 'relationship': 855, 'nowhere': 722, 'heterosexual': 489, 'encounters': 311, 'absurd': 13, 'dance': 231, 'stereotyped': 1009, 'pass': 765, 'million': 676, 'miles': 675, 'wasted': 1169, 'could': 213, 'spent': 992, 'starving': 1005, 'aids': 38, 'africa': 28, 'simply': 961, 'remade': 856, 'fails': 358, 'capture': 157, 'flavor': 390, 'terror': 1060, '1963': 3, 'title': 1096, 'liam': 597, 'neeson': 704, 'excellent': 338, 'always': 49, 'holds': 493, 'exception': 340, 'owen': 751, 'wilson': 1197, 'feel': 372, 'character': 171, 'luke': 630, 'major': 639, 'fault': 369, 'version': 1145, 'strayed': 1021, 'shirley': 948, 'jackson': 548, 'attempts': 78, 'grandiose': 438, 'thrill': 1084, 'earlier': 299, 'trade': 1107, 'snazzier': 972, 'special': 990, 'effects': 303, 'enjoy': 316, 'friction': 403, 'older': 733, 'horrible': 496, 'wasn': 1167, 'continuous': 211, 'minute': 677, 'fight': 377, 'chance': 169, 'development': 255, 'busy': 147, 'running': 891, 'sword': 1043, 'emotional': 309, 'attachment': 76, 'except': 339, 'machine': 633, 'wanted': 1163, 'destroy': 253, 'blatantly': 120, 'stolen': 1016, 'lotr': 621, 'wars': 1165, 'matrix': 652, 'examples': 337, 'ghost': 421, 'final': 382, 'yoda': 1226, 'obee': 723, 'vader': 1141, 'spider': 993, 'beginning': 102, 'frodo': 405, 'attacked': 77, 'return': 869, 'kings': 572, 'elijah': 306, 'wood': 1204, 'victim': 1147, 'both': 126, 'wait': 1160, 'hypnotizes': 512, 'stings': 1013, 'wraps': 1217, 'uh': 1126, 'hello': 481, 'vs': 1159, 'humans': 506, 'terminator': 1057, 'someone': 981, 'tell': 1054, 'nazi': 700, 'juvenile': 560, 'line': 604, 'rushed': 892, 'conclusion': 203, 'adult': 26, 'either': 305, 'disappointment': 270, 'save': 897, 'remember': 858, 'cinema': 180, 'dark': 234, 'places': 787, 'nervous': 705, '74': 9, '75': 10, 'dad': 229, 'sister': 964, 'newbury': 708, 'berkshire': 106, 'england': 314, 'tigers': 1089, 'snow': 974, 'appearance': 64, 'grizzly': 446, 'adams': 23, 'actor': 19, 'dan': 230, 'haggery': 458, 'think': 1077, 'shot': 950, 'dies': 264, 'anyone': 61, 'knows': 575, 'dvd': 297, 'etc': 327, 'please': 794, 'fitness': 388, 'club': 188, 'shame': 944, 'nearest': 701, '20': 6, 'hear': 477, 'others': 745, 'against': 32, 'stinkers': 1014, 'nominated': 716, 'golden': 434, 'globe': 428, 'female': 375, 'renaissance': 860, 'painter': 759, 'mangled': 645, 'recognition': 848, 'complaint': 198, 'liberties': 598, 'facts': 356, 'perfectly': 771, 'fine': 384, 'accounts': 14, 'artist': 72, 'dishwater': 275, 'dull': 296, 'script': 919, 'suppose': 1035, 'weren': 1183, 'enough': 318, 'naked': 697, 'factual': 357, 'hurriedly': 510, 'capped': 155, 'summary': 1032, 'saved': 898, 'ourselves': 747, 'couple': 217, 'hours': 501, 'favored': 370, 'brevity': 134, 'die': 262, 'sequels': 935, 'surprise': 1040, '1990s': 5, 'glut': 429, 'cashed': 164, 'wrong': 1222, 'guy': 454, 'concept': 201, 'cliffhanger': 184, 'mountain': 687, 'rescue': 862, 'sly': 971, 'stop': 1018, 'stallone': 999, 'nit': 713, 'pickers': 781, 'especially': 326, 'expert': 347, 'climbing': 185, 'base': 92, 'jumping': 557, 'aviation': 81, 'facial': 354, 'expressions': 348, 'full': 409, 'excuses': 342, 'dismiss': 276, 'overblown': 750, 'pile': 785, 'junk': 558, 'acted': 16, 'horse': 498, 'lovable': 623, 'undeniably': 1130, 'romp': 883, 'plenty': 795, 'thrills': 1086, 'unintentionally': 1134, 'laughs': 585, 'john': 553, 'lithgows': 607, 'sneery': 973, 'evilness': 335, 'tick': 1088, 'box': 130, 'baddies': 89, 'permanently': 776, 'harassed': 468, 'hapless': 463, 'turncoat': 1121, 'agent': 34, 'rex': 872, 'linn': 606, 'travers': 1110, 'henry': 485, 'rooker': 885, 'noteworthy': 719, 'cringe': 221, 'worthy': 1214, 'hal': 460, 'insists': 531, 'constantly': 208, 'shrieking': 955, 'painful': 756, 'disbelief': 271, 'captors': 156, 'hurt': 511, 'anybody': 59, 'whilst': 1189, 'surely': 1038, 'ralph': 835, 'waite': 1161, 'frank': 401, 'grinning': 445, 'girl': 422, 'plummets': 798, 'mention': 664, 'former': 396, 'london': 612, 'burning': 145, 'craig': 218, 'fairbrass': 360, 'brit': 139, 'cropper': 224, 'using': 1139, 'football': 393, 'help': 482, 'needed': 703, 'judgement': 555, 'cares': 160, 'happen': 464, 'lower': 627, 'expectations': 343, 'turn': 1120, 'volume': 1157, 'qaulen': 830, 'wearing': 1177, 'helicopter': 479}